<?php

// $Id: xspf_playlist_node.module,v 1.1.2.12.2.12 2009/04/07 19:31:32 arthuregg Exp $

/**
 * @FILE provides content level integration for XSPF
 */


/* ********************************************** */
/* DRUPAL HOOKS                                   */
/* ********************************************** */

/**
 * Implementation of hook_menu().
 */
function xspf_playlist_node_menu() {
  $items = array();

  $items['node/%/xspf'] = array(
    'page callback' => 'xspf_playlist_node_view',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  // add content type links for admin
  if ($types = xspf_playlist_node_content_type_names(true)) {
    foreach ($types as $type => $name) {
      // paths for each content type
      $items['admin/settings/xspf_playlist/'. $type] = array(
        'title' => 'XSPF Playlist Settings: '. $type,
        'description' => 'XSPF '. $type .' settings',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('xspf_playlist_node_admin_content_type_form', $type),
        'access arguments' => array('administer xspf_playlist'),
      );
    }
  }

  return $items;
}


/**
 * Implementation of hook_perm().
 * @return array
 */
function xspf_playlist_node_perm() {
  return array('build playlist on node');
}


/**
 * Implementation of hook_form_alter().
 * Display a playlist builder on the node edit form and add configuration fields
 * to the XSPF Playlist admin settings form.
 *
 * @param string $form_id
 * @param array $form
 */
function xspf_playlist_node_form_alter(&$form, &$form_state, $form_id) {
  // Get the node types that xspf is enabled on.
  $node_types = variable_get('xspf_playlist_node_types', array());

  // Display playlist builder on node edit page
  if (isset($form['type']) && isset($node_types[$form['type']['#value']]) && user_access('build playlist on node') ) {
   // xspf_playlist_node_builder($form);
  }

  // modify the main XSPF form
  if ($form_id == 'xspf_playlist_admin_settings_form') {
    $form['content'] = array(
      '#type' => 'fieldset',
      '#title' => t('Content settings'),
      '#collapsible' => TRUE,
    );

    $form['content']['xspf_playlist_node_types'] = array(
     '#type' => 'select',
     '#multiple' => true,
     '#title' => t('Playlist enabled'),
     '#description' => t('Choose which content types you want to be able to use playlists on.'),
     '#options' => xspf_playlist_node_content_type_names(),
     '#default_value' => $node_types,
    );

    // we have the types, now display settings per type
    if ($types = xspf_playlist_node_content_type_names(true)) {
      foreach ($types as $value => $name) {
      	$links[] = l(t('!name settings', array('!name' => $name)), 'admin/settings/xspf_playlist/'. $value);
      }
      $display = theme('item_list', $links);
    }
    else {
    	$display = t('You need to enable a content type to use generate XSPF Playlists with.');
    }

    $form['content']['content_types'] = array(
      '#type' => 'markup',
      '#value' => $display,
    );
  }
}


/**
 * Per content type settings.
 * @param $form
 * @param $content_type
 *   string, drupal content type machine name
 * @return array
 */
function xspf_playlist_node_admin_content_type_form($form, $content_type) {
  $form = array();

  // set the the content type in the form
  $form['content_type'] = array(
    '#type' => 'value',
    '#value' => $content_type,
  );

  $form['display'] = array(
    '#value' => t('You can configure settings for content type: %type here.', array('%type' => $content_type)),
    '#type' => 'markup',
  );
  $form['content'] = array(
    '#type' => 'fieldset',
    '#title' => t('Select Playlist Files'),
  );
  // select what options will be used to build the playlist
  $form['content']['thetype_'. $content_type]['xspf_'. $content_type .'_use'] = array(
    '#type' => 'select',
    '#multiple' => true,
    '#title' => t('Build Playlist From Files'),
    '#options' => module_invoke_all('xspf_playlist_use', 'define', null, $content_type),
    '#default_value' => variable_get('xspf_'. $content_type .'_use', ''),
    '#description' => t('XSPF playlist will build its playlist from files associated with the items that you have selected.'),
  );

  // Add any config items that we've got
  // make an artifical node
  $my_node = new StdClass();
  $my_node->type = $content_type;
  foreach (variable_get('xspf_'. $content_type .'_use', array()) as $extension) {
    $form['content']['thetype_'. $content_type][] =  xspf_playlist_invoke_fire('xspf_playlist_use', 'config', $my_node, $extension);
  }

  $form['playlists'] = array(
    '#type' => 'fieldset',
    '#title' => t('Playlist Settings'),
  );

  // settings for item duration. Images need duration tags so that they rotate in the playlist
  $options = array_values(array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30));
  $form['playlists']['thetype_'. $content_type]['xspf_'. $content_type .'_duration'] = array(
    '#type' => 'select',
    '#title' => t('Image duration'),
    '#options' => $options,
    '#default_value' => variable_get('xspf_'. $content_type .'_duration', 10),
    '#description' => t('Image files in a playlist need to have a duration (in seconds) for which they are shown.'),
  );
  return system_settings_form($form);
}


/* ********************************************** */
/* CONTRIB HOOKS                                  */
/* ********************************************** */

/**
 * Implementation of hook_xspf_playlist_use().
 * @param string $op
 * @param object $node
 * @param $config
 */
function xspf_playlist_node_xspf_playlist_use($op, $node, $config, $data = null) {
  switch($op){
    case 'define':
      $types = array();
      if (module_exists('upload')) {
        $types['xspf_playlist_node--1'] = t('Drupal: Upload attached files.');
      }
      return $types;
      break;

    case 'config':
      switch($config) {
        case 1:
        break;
      }
    break;

    case 'views':
      switch ($config) {
        case 'playlist_file_source':
        case 'playlist_count' :
          $conditions = '%s.nid = upload.nid';
          return array('tablename' => 'upload', 'conditions' => $conditions);
        break;
      }
    break;

    case 'return':
      switch($config) {
        case 1:
          if ($node->files) {
            $items = xspf_playlist_node_get_files_from_node($node);
          }
        break;
      }
      if ($items) {
        return $items;
      }
    break;
  }
}


/**
 * integrate XSPF with the flvmediaplayer module to provide urls
 * @param string $op is the operation being called
 * @param string $name is the action name being called
 * @param array $config is an array of configuration values
 */
function xspf_playlist_node_flvmediaplayer_file_use($op, $name = NULL, $node = NULL, $config = NULL) {
  switch ($op) {
    case 'define':
      return array('xspf_playlist_node--1' => t('XSPF Playlist for each node'));
    break;
    case 'file':
      // make sure that there are files for this node
      if (xspf_playlist_node_items($node)) {
        return xspf_playlist_url('node/'. $node->nid .'/xspf');
      }
    break;
  }
}


/* ******************************************************* */
/* INTERNAL FUNCTIONS */
/* ******************************************************* */

/**
 * Landing page for producing the XSPF data
 * for a given node- node/X/xspf
 * @param $nid is a node id
 * @return string
 *   XSPF XML
 */
function xspf_playlist_node_view($nid) {
  // load the node
  $node = node_load($nid);
  // get the types of nodes that xspf is enabled on
  $types = variable_get('xspf_playlist_node_types', array());
  // make sure this node type is in the list
  if ($types[$node->type]) {
    // Check access and get the main files for this node.
    if ( $items = xspf_playlist_node_items($node)) {
      $playlist = array('title' => check_plain($node->title), 'items' => $items);
      xspf_playlist_render($playlist, 'node', $node->type, $node);
      return;
    }
  }
  // No content found.
  module_invoke_all('exit');
  exit;
}


/**
 * gets item data from nodes, for building a playlist
 * for a requested node.
 *
 * @param object $node is a drupal node object
 * @param int $limit
 * @return array of item arrays
 */
function xspf_playlist_node_items($node, $limit = null) {
  // Check to see if we should use any files
  if ($modules = variable_get('xspf_'. $node->type .'_use', null) ) {
    $items = array();
    $nodes = array();
    foreach (array_filter($modules) as $config) {
      if ($item = xspf_playlist_invoke_fire('xspf_playlist_use', 'return', $node, $config)) {
        // has a limit been set on how many items to return?
        if ($limit) {
          // correct the split for one off error
          $item = array_slice($item, 0, $limit);
          // increment our counter
          $nodes[$node->nid] = $nodes[$node->nid] + 1;
          if ($limit >= $nodes[$node->nid]) {
            $items = array_merge($items, $item);
          }
        }
        else {
          $items = array_merge($items, $item);
        }
      }
    }
  }
  return $items;
}


/**
 * assigns file data into the items array to create the playlist
 * @param $node
 *   node object
 * @param $filepath
 *   string is the file path
 * @retun array
 *   xspf item
 */
function xspf_playlist_node_create_file_item($node, $filepath) {
  $path_parts = pathinfo($filepath);
  if (_xspf_playlist_filetype_supported($path_parts['extension'])) {
    return xspf_playlist_node_build_file_item($node, $filepath);
  }
}


/**
 * retrieves files from a node and places them in item
 * format for playlist
 * @param $node is a drupal node object
 * @return array of items
 */
function xspf_playlist_node_get_files_from_node($node) {
  $items = array();
  // loop through files
  if (isset($node->files)) {
    foreach ($node->files as $file) {
      // get file data
      if ($item = xspf_playlist_node_create_file_item($node, xspf_playlist_url($file->filepath))) {
        // set the title to the file name description only if it is different than
        // the file name to force the description to be human set
        if (isset($file->description) && ($file->description != $file->filename )) {
          _xspf_playlist_item_set_value($item, 'title', check_plain($file->description));
        }
        $items[] =  $item;
      }
    }
  }
  return $items;
}


/**
 * assigns file data into the items array to create the playlist
 * this does not check incoming data so that other modules can
 * use this format to build a playlist item w/o xspf interfeering
 * @param object $node node object
 * @param string $url url to file that is being added to the items array
 */
function xspf_playlist_node_build_file_item($node, $url) {
  $item = array();
  $item[] = array(
    'key' => 'creator',
    'value' => check_plain($node->name),
  );

  $item[] = array(
    'key' => 'location',
    'value' => $url,
  );

  // Link to playlist item
  $item[] = array(
    'key' => 'info',
    'value' => xspf_playlist_url('node/'. $node->nid),
  );

  // only return last three chars of file type as the type
  if ($path_parts = pathinfo($url) ) {
    $item[] = array(
      'key' => 'meta',
      'value' => $path_parts['extension'],
      'attributes' => array(
        'rel' => 'type',
      ),
    );
  }

  // we need to see if we need to set the duration tag
  if (in_array(strtolower($type), array('jpg', 'gif', 'png'))) {
    $item[] = array(
      'key' => 'duration',
      'value' => variable_get('xspf_'. $node->type .'_duration', 10),
    );
  }

  $item[] = array(
    'key' => 'title',
    'value' => check_plain($node->title),
  );

  $item[] = array(
    'key' => 'identifier',
    'value' => $node->nid,
  );

  xspf_playlist_build_item($item, $node, $url, $thumb, $meta);
  return $item;
}


/* ******************************************************* */
/* SETTINGS                                                */
/* ******************************************************* */

/**
 * builds the options for a node to choose thumbnails per file
 * @param array $form is a drupal form array
 */
function xspf_playlist_node_builder(&$form) {
  // get all the thumbs
  $thumbs = xspf_playlist_node_thumbs($form['#node']);
  // make it obvious that we've got thumbnails
  $form['xspf_thumbnails'] = array(
    '#type' => 'value',
    '#value' => $thumbs,
  );
  $form['xspf_playlist'] = array(
    '#type' => 'fieldset',
    '#title' => t('Playlist builder'),
    '#description' => t('You can define options for the playlist (if any) on this node here'),
    '#collapsible' => true,
    '#collapsed' => false,
  );
  // get all the files for this node
  $items = xspf_playlist_node_get_files_from_node($form['#node']);
  $form['xspf_thumbnails_items'] = array(
    '#type' => 'value',
    '#value' => $items,
  );
  foreach($items as $xid => $item) {
    $file = pathinfo(_xspf_playlist_item_get_value($item, 'location'));
    $form['xspf_playlist']['xspf_playlist_thumb_'. $xid] = array(
      '#type' => 'select',
      '#title' => $file['basename'],
      '#options'  => $thumbs,
      // Find default from the thumb if already set.
      '#default_value' => array_search(_xspf_playlist_item_get_value($item, 'image'), $thumbs),
      '#description' => t('Select a thumbnail for this file.'),
      '#attributes' => array('class' => 'xspf_thumb_select'),
    );

    $form['xspf_playlist']['xspf_'. $xid] = array(
      '#type' => 'markup',
      '#value' => theme('xspf_playlist_thumbnailer_picker', $thumbs, $xid),
    );

  }
}


/**
 * Build a list of content type names, either enabled types or all types
 * @param $enabled
 *   boolean
 * @return array
 */
function xspf_playlist_node_content_type_names($enabled = false) {
  static $content_types, $return_types;

  if (! $content_types) {
    // get all the content types and put them into an array
    $types = _node_types_build();
    foreach($types[0] as $type){
      $content_types[$type->type] = $type->name;
    }
  }

  if (! $enabled) {
    return $content_types;
  }

  if (! $return_types) {
    $return_types = array();
    // get the enabled content types
    $node_types = variable_get('xspf_playlist_node_types', array());
    foreach ($node_types as $node_type) {
      $return_types[$node_type] = $content_types[$node_type];
    }
  }
  return $return_types;
}